services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registros_backend_api
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8000:8000"  # Exponemos directo el puerto 8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - uploads_data:/app/uploads
    user: "1000:1000"
    networks:
      - prisma-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M

  db:
    image: postgres:17.6-alpine3.22
    container_name: registros_backend_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Guayaquil
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - /etc/localtime:/etc/localtime:ro
    networks:
      - prisma-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:9.0-alpine
    container_name: registros_backend_valkey
    restart: unless-stopped
    volumes:
      - valkey_prod_data:/data:Z
      - /etc/localtime:/etc/localtime:ro
    command: valkey-server --appendonly yes --requirepass ${VALKEY_PASSWORD:-changeme}
    networks:
      - prisma-network

networks:
  prisma-network:

volumes:
  postgres_data:
  valkey_prod_data:
  uploads_data: