version: '3.8'

services:
  registros_backend:
    build: .
    container_name: registros_backend
    restart: always
    environment:
      # Conexión a NeonDB (desde el .env)
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      # Mantiene las imágenes guardadas en la carpeta física
      - ./uploads:/app/uploads
    env_file:
      - .env