version: '3.8'

services:
  registros_db:
    image: postgres:15-alpine
    container_name: registros_db
    restart: always
    environment:
      POSTGRES_USER: user_tesis
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_tesis
    ports:
      - "5432:5432"

  registros_backend:
    build: .
    container_name: registros_backend
    environment:
      DATABASE_URL: "postgresql://user_tesis:password123@registros_db:5432/db_tesis?schema=public"
      JWT_SECRET: "tu_secreto_local"
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - registros_db